# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import molmo_pb2 as molmo__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in molmo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MolmoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PointQA = channel.unary_unary(
                '/molmo.MolmoService/PointQA',
                request_serializer=molmo__pb2.PointQARequest.SerializeToString,
                response_deserializer=molmo__pb2.PointQAResponse.FromString,
                _registered_method=True)


class MolmoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PointQA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MolmoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PointQA': grpc.unary_unary_rpc_method_handler(
                    servicer.PointQA,
                    request_deserializer=molmo__pb2.PointQARequest.FromString,
                    response_serializer=molmo__pb2.PointQAResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'molmo.MolmoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('molmo.MolmoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MolmoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PointQA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/molmo.MolmoService/PointQA',
            molmo__pb2.PointQARequest.SerializeToString,
            molmo__pb2.PointQAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
